version: "3"
services:
  server:
    command: socat TCP-L:12345,fork,reuseaddr >  EXEC:'sqlite3 /opt/sqlite/db',pty
    build: .
    volumes:
      - /tmp/sqlitedbs/test:/opt/sqlite/db
    networks:
      - sqlnet
  proxy:
    command: socat TCP-L:12346,fork,reuseaddr TCP:server:12345
    build: .
    ports:
      - 12346:12346
    networks:
      - sqlnet
networks:
  sqlnet:
    driver: bridge