
GET https://lseg-widgets.financial.com/rest/api/find/securities?fids=x._TICKER,x._DSPLY_NAME,x._ISIN,x._TYPE,x._LOCAL_ID&search=&searchFor=ISIN&exchanges=MUN&pageSize=100000&pageNo=0&secTypes=STO
Content-Type: application/json; charset=utf-8
jwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsZ24iOiJXR19CT0VSU0VNVUVOQ0hFTkZUQSIsIm5iZiI6MTczMzk1ODI3MSwicHJ0Ijoid2xpYl9ibXVuIiwiaXNzIjoiZmluY29tIiwicHJtIjpbImE6c3RyZWFtaW5nIiwiYzpiYmFnIiwiYzp3bV9kYXRhIiwiVVNFUiJdLCJldHkiOiJXR19CT0VSU0VNVUVOQ0hFTkZUQSIsImV4cCI6MTczMzk1ODU3NiwiaWF0IjoxNzMzOTU4Mjc2LCJqdGkiOiIwY2IwZWY0MS0zM2E5LTQ0Y2EtOWM0ZC1jMTE0OGVjNzk1ZGEiLCJkaWQiOiJXR19CT0VSU0VNVUVOQ0hFTkZUQSIsInNlYSI6IjFiZWMzY2MzLWQ3N2YtNDExMC1hZTQ3LWJhMmFjOTJhMGE5ZSJ9.qyzf1Gi5cSURXNOU7Hkt76HQ772iaIXOsH9ZiNI2uo8
