
GET https://custom.resbank.co.za/SarbWebApi/WebIndicators/Shared/GetTimeseriesObservations//MMSD008A
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Accept: application/json, text/javascript, */*; q=0.01
